[2024-12-30T08:48:40.348+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-30T08:48:40.361+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag_v2.second_task manual__2024-12-30T08:48:38.415988+00:00 [queued]>
[2024-12-30T08:48:40.367+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag_v2.second_task manual__2024-12-30T08:48:38.415988+00:00 [queued]>
[2024-12-30T08:48:40.368+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-30T08:48:40.377+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): second_task> on 2024-12-30 08:48:38.415988+00:00
[2024-12-30T08:48:40.382+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=551) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-30T08:48:40.383+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'first_dag_v2', 'second_task', 'manual__2024-12-30T08:48:38.415988+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/bash_operator_dag.py', '--cfg-path', '/tmp/tmp1gpmrmm4']
[2024-12-30T08:48:40.385+0000] {standard_task_runner.py:72} INFO - Started process 552 to run task
[2024-12-30T08:48:40.385+0000] {standard_task_runner.py:105} INFO - Job 12: Subtask second_task
[2024-12-30T08:48:40.415+0000] {task_command.py:467} INFO - Running <TaskInstance: first_dag_v2.second_task manual__2024-12-30T08:48:38.415988+00:00 [running]> on host b0ef9544b3b5
[2024-12-30T08:48:40.462+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tanzid' AIRFLOW_CTX_DAG_ID='first_dag_v2' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-30T08:48:38.415988+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-30T08:48:38.415988+00:00'
[2024-12-30T08:48:40.463+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-30T08:48:40.474+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-30T08:48:40.475+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world, this is the second task following first task']
[2024-12-30T08:48:40.482+0000] {subprocess.py:99} INFO - Output:
[2024-12-30T08:48:40.483+0000] {subprocess.py:106} INFO - hello world, this is the second task following first task
[2024-12-30T08:48:40.483+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-12-30T08:48:40.499+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-30T08:48:40.499+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=first_dag_v2, task_id=second_task, run_id=manual__2024-12-30T08:48:38.415988+00:00, execution_date=20241230T084838, start_date=20241230T084840, end_date=20241230T084840
[2024-12-30T08:48:40.519+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-30T08:48:40.533+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-30T08:48:40.542+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
